name: Test schema

on:
  push:
    paths:
    - "enmity-theme.schema.json"
    - "sample.json"
    - ".github/workflows/test.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
    - 
      uses: actions/setup-python@v3
    -
      name: Convert schema to JSON
      shell: pwsh
      run: | 
        python -c @"
        import json, yaml
        with open('enmity-theme.schema.json', 'w') as f, open('enmity-theme.schema.yaml') as fp:
            f.write(json.dumps(yaml.safe_load(fp)))
        "@

    - 
      name: Validate sample.json against schema
      shell: pwsh
      run: |
        Test-Json -Json (Get-Content .\sample.json | Out-String) -SchemaFile .\enmity-theme.schema.json
    -
      name: Validate published themes against schema
      shell: pwsh
      run: |
        $success = $true
        $knownThemes = @("https://raw.githubusercontent.com/compilekaiten/Enmity-Themes/main/Zelk/Zelk.json",
                         "https://raw.githubusercontent.com/pwnPwner/catppuccin/main/catppuccin.json",
                         "https://rosieorthinanos.dev/Emerald.json",
                         "https://rosieorthinanos.dev/Orthinanos.json",
                         "https://raw.githubusercontent.com/Leizurly/discord-sultan/main/sultan.json",
                         "https://raw.githubusercontent.com/redstonetechwiz/pastelcord/main/discalm.json",
                         "https://raw.githubusercontent.com/Leizurly/discord-flashbang/f047332d9b3baf83686c94979838a5da84876877/flashbang.json",
                         "https://raw.githubusercontent.com/sudo9000/enmity-BozoTheClown-Theme/master/BozoTheClown.json",
                         "https://static.itsnebula.net/lotus.json",
                         "https://static.itsnebula.net/tokyonight.json",
                         "https://static.itsnebula.net/mist.json",
                         "https://static.itsnebula.net/mars.json",
                         "https://static.itsnebula.net/dracula.json",
                         "https://raw.githubusercontent.com/sudo9000/enmity-Blu-Theme/master/Blu.json",
                         "https://raw.githubusercontent.com/discord-modifications/enmity-addons/main/Themes/AMOLED.json"
                        )
        $knownThemes | ForEach-Object {
          Write-Output "Validating $_ against schema"
          try {
            Test-Json -Json (Invoke-WebRequest -UseBasicParsing $_) -SchemaFile ./enmity-theme.schema.json > $null
          } catch {
            $success = $false
            Write-Output "Validation of $_ failed"
            Write-Output $_
          }
        }
        if (-not $success) {
          throw "Failed validation of working themes"
        }
    -
      name: Test if broken themes properly fail
      shell: pwsh
      run: |
        $failed = $false
        $knownBadThemes = @(
                            "https://raw.githubusercontent.com/discord-modifications/enmity-addons/main/Themes/DarkDiscord.json"
                           )
        $knownBadThemes | ForEach-Object {
          Write-Output "Validating $_ against schema"
          try {
            Test-Json -Json (Invoke-WebRequest -UseBasicParsing $_) -SchemaFile ./enmity-theme.schema.json > $null
          } catch {
            $failed = $true
            Write-Output "Validation of schema failed (expected)"
            Write-Output $_
          }
        }
        
        if (-not $failed) {
          throw "Bad theme was successfully validated"
        }
  build-docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      -
        uses: actions/setup-python@v3
      - 
        name: Setup JSON Schema for Humans
        run: |
          python -m venv env/ && source env/bin/activate
          pip install json-schema-for-humans pyyaml
      -
        name: Convert schema to JSON
        shell: pwsh
        run: | 
          python -c @"
          import json, yaml
          with open('enmity-theme.schema.json', 'w') as f, open('enmity-theme.schema.yaml') as fp:
              f.write(json.dumps(yaml.safe_load(fp)))
          "@
      -
        name: Build schema website
        run: |
          mkdir -p public
          env/bin/generate-schema-doc --config expand_buttons=true --config link_to_reused_ref=false enmity-theme.schema.yaml public/index.html
          cp enmity-theme.schema.json public/
          touch public/.nojekyll
      -
        name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: github.ref == 'refs/heads/trunk'
        with:
          branch: gh-pages
          folder: public
          git-config-name: GitHub Actions
          git-config-email: github-actions[bot]@users.noreply.github.com
          single-commit: true



